  publish = "build" # Ensure this points to your build folder
  command = "npm run build" # Adjust this if your build command is different
 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "netlify/functions"
  publish = "frontend/build"  # if you also have frontend build here

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
